### ISSUE TITLE
Cobertura de Testes Code Climate

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-eps-mds/2020.1-Grupo2-wiki#100]
# Descrição
Esta Issue requer que a cobertura de testes seja demonstrada nos READMEs dos repositorios, com dados providenciados pelo Code Climate

## Material de apoio
- [(Code Climate) Getting Started Test Coverage](https://docs.codeclimate.com/docs/getting-started-test-coverage)

**Comment by joaovitorml** [comment]
Foi concluída nos dois repositórios
