### ISSUE TITLE
Configurar Lint com Guia de Estilo

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-eps-mds/2020.1-Grupo2-wiki#101]
# Descrição

Esta Issue requer que se configure a utilização do Lint selecionado ([ver mais](https://github.com/fga-eps-mds/2020.1-GaiaDex-wiki/tree/develop/docs/document_style_guide))

## Material de Apoio

- [<Medium> Install ESLint global with Airbnb-style-guide and use it in VSCode.](https://medium.com/medvine/install-eslint-global-with-airbnb-style-guide-and-use-it-in-vscode-d752dfa40b21)
- [(Doc Oficial da Airbnb) npm:A babel preset for transforming your JavaScript for Airbnb.](https://www.npmjs.com/package/babel-preset-airbnb)
- [(Doc Oficial da Airbnb) npm:This package provides Airbnb's .eslintrc as an extensible shared config](https://www.npmjs.com/package/eslint-config-airbnb)

**Comment by joaovitorml** [comment]
Lint configurado, issue fechada
