### ISSUE TITLE
Pesquisa sobre refatoração no Backend

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-eps-mds/2020.1-Grupo2-wiki#102]
# Descrição
Esta Issue requer que seja feito um rastreamento no repositorio do Backend para identificar se há necessidade ou não de alterações na arquitetura geral (seja de pastas, ou do proprio codigo em si)

## **Sugestão** de Pesquisa

> **Vale ressaltar que não é necessario acessar todo esse material, mas que este pode ser de bastante utilidade*.

- [ ] [Refactoring Guru *(Principal fonte sobre Design Patterns na internet)*](https://refactoring.guru/pt-br)

------------------------------

- [ ] [Stoplight.io](https://stoplight.io/documentation/) vs [Swagger](https://swagger.io) -- qual usar?
    - Uso do Swagger com Express.js
        - [ ] [How to add Swagger UI to existing Node js and Express.js project](https://medium.com/@kirtikau/how-to-add-swagger-ui-to-existing-node-js-and-express-js-project-2c8bad9364ce)
        - [ ] [Documenting your Express API with Swagger](https://blog.logrocket.com/documenting-your-express-api-with-swagger/)
    - Uso do Spotlight com Express.js
        - [ ] [Spotlight:API Development Guide & Support](https://stoplight.io/api-development-guide/)
        - [ ] [https://survivejs.com/blog/express-gateway-interview/](https://survivejs.com/blog/express-gateway-interview/)

------------------------------

- [ ] [Design Patterns em Express.js](https://dzone.com/articles/design-patterns-in-expressjs)

------------------------------

- [ ] [Exemplos de organização (dependendo do tipo de projeto) do próprio Express.js](https://github.com/expressjs/express/tree/master/examples)

------------------------------

- [ ] [JavaScript Design and Architectural Patterns](https://medium.com/@hjkmines/javascript-design-and-architectural-patterns-cfa900c6fe41)

------------------------------

- [ ] [Parte 1 -> Fundamental Node.js Design Patterns](https://blog.risingstack.com/fundamental-node-js-design-patterns/)
- [ ] [Parte 2 -> Node.js Best Practices - Part 1](https://blog.risingstack.com/node-js-best-practices/)
    - [ ] [lib async, sugerida no artigo](https://github.com/caolan/async)
- [ ] [Parte 3 -> Node.js Best Practices - Part 2](https://blog.risingstack.com/node-js-best-practices-part-2/)

------------------------------

- [ ] [Repositório exemplo que possivelmente foi implementado com boas práticas](https://github.com/Ventrosky/pony-express)

------------------------------

- [ ] [Guia/Compilado de boas práticas em Node.js (50k de estrelas no github)](https://github.com/goldbergyoni/nodebestpractices)

------------------------------

- [ ] [Design patterns in Node.js: A practical guide](https://blog.logrocket.com/design-patterns-in-node-js/)

------------------------------

- [ ] [Design patterns for modern web APIs](https://blog.feathersjs.com/design-patterns-for-modern-web-apis-1f046635215)

**Comment by joaovitorml** [comment]
Refatoração feita, issue fechada
