### ISSUE TITLE
Evolução do Protótipo

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-eps-mds/2020.1-Grupo2-wiki#104]
# Descrição
Evoluir protótipo para consertar erros de dimensionamento*, assim como a adição de pop-ups e outras telas relevantes (como, por exemplo, a de configuração de notificações de *Minha Planta*)

\*
![image](https://user-images.githubusercontent.com/23236957/96313310-02de1100-0fe4-11eb-9030-14e2deb4d7d0.png)

[link para prototipo](https://www.figma.com/file/aZt1BiKEaVJilKd3aXWRcl/GaiaDex---Revamp?node-id=1%3A206)

**Comment by joaovitorml** [comment]
Foi concluído
