### ISSUE TITLE
Readequar issues do FrontEnd para incluir a distinção entre as fases da entrega

### ISSUE THREAD

**Issue by guilhermedelyra** [fga-eps-mds/2020.1-Grupo2-wiki#105]
# Descrição
Esta Issue requer que, nas issues do FrontEnd, seja especificado qual etapa daquela história será realizada:
1. Wireframe (apenas o layout cru da tela)
2. UI (layout + imagens, botões, fontes de acordo com o prototipo)
3. Versão Final (inclusão de animações e outros adornos que sejam considerados relevantes)

**Comment by joaovitorml** [comment]
Não será feito
