### ISSUE TITLE
React Training 

### ISSUE THREAD

**Issue by senaarth** [fga-eps-mds/2020.1-Grupo2-wiki#22]
# Description
MDS and EPS teams should study the technology to be able to start the project.

# Objectives
- [ ] React Native tutorial João Vítor
- [x] React Native tutorial Rafael Makaha
- [x] React Native tutorial Lyra
- [ ] React Native tutorial Arthur
- [ ] React Native tutorial Marcos Felipe
- [ ] React Native tutorial Marcos Gabriel
- [ ] React Native tutorial Antônio Ruan
- [ ] React Native tutorial Victor Hugo
- [ ] React Native tutorial Victor Samuel
- [ ] React Native tutorial Vinícius Vieira

**Comment by rafaelmakaha** [comment]
Issue cancelada
